<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deployment" nsURI="http://eu.chorevolution/modelingnotations/deployment"
    nsPrefix="deployment">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//ServiceDependency"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceType" lowerBound="1"
        eType="#//ServiceTypes" defaultValueLiteral="SOAP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDependency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceSpecName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceSpecRole" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceTypes">
    <eLiterals name="SOAP"/>
    <eLiterals name="REST" value="1"/>
    <eLiterals name="COAP" value="2" literal="COAP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PackageType">
    <eLiterals name="COMMAND_LINE"/>
    <eLiterals name="TOMCAT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployableServiceSpec" eSuperTypes="#//ServiceSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="replacementService" upperBound="-1"
        eType="#//ServiceSpec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageUri" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageType" lowerBound="1"
        eType="#//PackageType" defaultValueLiteral="TOMCAT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cloudAccount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfInstances" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceImpact" lowerBound="1"
        eType="#//ResourceImpact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="haDeployment" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syslogServerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyServiceSpec" eSuperTypes="#//ServiceSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceSpec" lowerBound="1"
        eType="#//ServiceSpec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//LegacyServiceInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyServiceInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceSpec" lowerBound="1"
        eType="#//LegacyServiceSpec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoreographySpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployableServices" upperBound="-1"
        eType="#//DeployableServiceSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choreography">
    <eStructuralFeatures xsi:type="ecore:EReference" name="choreographySpec" lowerBound="1"
        eType="#//ChoreographySpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployableServices" upperBound="-1"
        eType="#//DeployableService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyServices" eType="#//LegacyService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployableService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloudNodes" upperBound="-1"
        eType="#//CloudNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//ServiceInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloudNode" lowerBound="1"
        eType="#//CloudNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceSpec" lowerBound="1"
        eType="#//DeployableServiceSpec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloudNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceImpact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuImpact" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ramImpact" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diskSpeedImpact" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diskCapacityImpact" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkingImpact" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
</ecore:EPackage>
